### ISSUE TITLE
Issue with GCODE automation for system shutdown

### ISSUE THREAD

**Issue by Jimboski711** [jneilliii/OctoPrint-WemoSwitch#10]
Hello great plug in.  I am having an issue where I have the plugin working via Gcode from the terminal in Octoprint but my use case is to use the M81 or @wemooff commands to automatically shut power down when a print completes.  I have tried adding both commands to CURA under End Code and in Octoprint under "When Print Completes"  I did have it work once but it was random and no longer works.  If I take the Gcode I have in my end script and copy and paste it into the terminal after a print completes it works.  The one time it worked randomly was after I added a wait command G4 P5000 to wait 5 seconds before sending the shutdown command M81 MYIP or @WEMOOFF MyIP.

Just wondering if anyone has had success with this scenario and could share the successful End Code in Cura or "After Print Completes " Code in Octoprint to shut power off after a complete print

**Comment by jneilliii** [comment]
I assume your plug with the IP you are using had the gcode option enabled in plugin settings?

**Comment by Jimboski711** [comment]
Jim Guiette - CISSP CCSP
Enterprise Security Services Leader
Information Security Services

Sent from my iPad
________________________________

**Comment by Jimboski711** [comment]
Yes that's correct - Like I said I can turn the plug on and off from the terminal mode by hand entering in the gcode but if I add the Gcode to the print complete area in Octoprint it does not work.  Other commands do though so as an example I can turn the fans on - set a timer ect when the print completes .  It just does not seem to recognize the Gcode command to power the wemo off.  I can even copy the Gcode from the Print Complete area of Octoprint and paste it into the terminal and it works.  Just doesn't work when the print completes

**Comment by jneilliii** [comment]
Ok, I'll do some testing on my end and see. Do you have any errors in octoprint.log?

**Comment by MrDogbert** [comment]
Hi @jneilliii 
I'm having the same issue as @Jimboski711 ...
M81 MYIP or @WEMOOFF MyIP work fine typing them into the terminal line,
But from either Octoprint's GCode scripts "After print job completes", or putting direct at the end of the GCode file (manually, or within Cura's end script section) it does not work at all.
If it helps, I'm running Octoprint 1.3.9
GCode option is enabled in the options.

Thankyou for the Awesome plugin! Was really after a Wemo plugin!

**Comment by jneilliii** [comment]
I just thought of something but haven't checked the code yet, do you guys have warn while printing enabled?

**Comment by Jimboski711** [comment]
I have Warn While Printing and Warning Prompt both selected.  Also Auto Connect and Auto Disconnect with 10 and 5 seconds.    I do not have Run System Connands on.   I have not checked any log files but could if you sent me the high level instructions on how to enable them and get them.

Jim Guiette - CISSP CCSP
Enterprise Security Services Leader
Information Security Services

Sent from my iPad
________________________________

**Comment by jneilliii** [comment]
I think if you set the gcode off delay it will resolve the problem. What is happening is the warn while printing option is blocking the gcode off command as the printer is technically still printing when it receives the instruction. This was to avoid instances where people had a delay set and started a new print. By setting the delay the printing status is not printing when that instruction is received and it should work as expected. The other option would be to uncheck the warn while printing option.

**Comment by MrDogbert** [comment]
Hi @jneilliii ,
You are right about the Set GCode Off Delay - I checked the logs from before putting in a delay. This is what it showed:
22:44:02,252 - octoprint.util.comm - INFO - Finished in 3781.195 s.
22:44:02,253 - octoprint.util.comm - INFO - Changing monitoring state from "Printing" to "Finishing"
22:44:02,265 - octoprint.plugins.DeleteAfterPrint - INFO - Printing succesfull!
22:44:02,266 - octoprint.plugins.DeleteAfterPrint - INFO - Try unselect file
22:44:02,269 - octoprint.plugins.DeleteAfterPrint - INFO - ...wait for printer being ready...attempt:1
22:44:03,272 - octoprint.plugins.DeleteAfterPrint - INFO - ...wait for printer being ready...attempt:2
22:44:04,274 - octoprint.plugins.DeleteAfterPrint - INFO - ...wait for printer being ready...attempt:3
22:44:05,278 - octoprint.plugins.DeleteAfterPrint - INFO - ...wait for printer being ready...attempt:4
22:44:06,280 - octoprint.plugins.DeleteAfterPrint - INFO - Ready:::False
22:44:06,282 - octoprint.plugins.DeleteAfterPrint - INFO - Unselect file
22:44:06,351 - octoprint.plugins.DeleteAfterPrint - INFO - File deleted.
22:51:27,267 - octoprint.plugins.wemoswitch - INFO - Not powering off PRINTER_1 because printer is printing.
22:51:28,320 - octoprint.util.comm - INFO - Changing monitoring state from "Finishing" to "Operational"
22:52:24,034 - octoprint.util.comm - INFO - Changing monitoring state from "Operational" to "Offline" 

I initially put only a 3 second delay and it worked great!
I've since increased the delay to 300 seconds to give the hotend sufficient time to fan cool.

Tested in the Octoprint "After print job completes" section with both M81 MYIP or @WEMOOFF MyIP...
Each one worked fine. I like the @WEMOOFF version purely because it's less gcode commands to remember. :)

If you're planning on putting out an update, could I possibly suggest a default 1 second delay for the gcode Off, so that if gcode off is checked and there is nothing in the delay box, it will default to 1 second ?
This should make it work without needing lots of troubleshooting.

Thankyou again for such an Awesome plugin! :)


Also, just a side note, I noticed in the logs it really does not like it when you call the Wemo by name (rather than IP):
Hope this helps...

2018-11-20 06:12:52,684 - octoprint.util.comm - ERROR - Error while processing hook wemoswitch for phase queuing and command M81 PRINTER_1:
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 3064, in _process_command_phase
    hook_results = hook(self, phase, command, command_type, gcode, subcode=subcode, tags=tags)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_wemoswitch/__init__.py", line 220, in processGCODE
    if plug["gcodeEnabled"]:
TypeError: 'NoneType' object has no attribute '__getitem__'
2018-11-20 06:13:41,035 - octoprint.util.comm - ERROR - Error while processing hook wemoswitch for phase queuing and command M81PRINTER_1:
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 3064, in _process_command_phase
    hook_results = hook(self, phase, command, command_type, gcode, subcode=subcode, tags=tags)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_wemoswitch/__init__.py", line 220, in processGCODE
    if plug["gcodeEnabled"]:
TypeError: 'NoneType' object has no attribute '__getitem__'
2018-11-20 06:14:23,665 - octoprint.util.comm - ERROR - Error while processing hook wemoswitch for phase queuing and command M80 PRINTER_1:
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 3064, in _process_command_phase
    hook_results = hook(self, phase, command, command_type, gcode, subcode=subcode, tags=tags)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_wemoswitch/__init__.py", line 211, in processGCODE
    if plug["gcodeEnabled"]:
TypeError: 'NoneType' object has no attribute '__getitem__'
