### ISSUE TITLE
Can I turn on the Switch/Printer via the Terminal and M80?

### ISSUE THREAD

**Issue by jkkato** [jneilliii/OctoPrint-WemoSwitch#14]
First off, Thanks for your plug in.

I was wondering if I could turn ON my printer (which is connected to the WEMO switch), via the terminal? For instance, I was using OctoRemote on my phone. It doesn't have the thunderbolt icon at the top (obviously) linked to your plugin, but I thought I would try the M80 command in the Terminal.

I am guessing, that since the printer is not connected (as it is powered off), the terminal does not send any commands. I tried sending the M80 (ipaddress) command from OctoRemote's terminal and it looks like nothing happens. The Octoprint terminal won't even let me type in anything.

I do have the GCodeTrigger enabled and can M81 (ipaddress) the switch/printer off from the terminal. Is there any other way to turn on the WEMO switch remotely (not on the Octoprint interface)? Not a huge deal either way.

**Comment by jneilliii** [comment]
Yeah, the `M80 (ip address)` command would power on the plug, but requires the printer to be connected. It's really there for those wanting to control things other than the printer's power, ie extra lights, fans, etc. Since you can't type in the terminal than it wouldn't work for you. If you were to enable a virtual printer you could be connected to that and send the command then swap the connection after your printer was powered on, but that seems like a pain. I do however think OctoRemote integrated support for my TPLinkSmartplug in the app, so you may be able to request this plugin to be supported as well.
