### ISSUE TITLE
Takes over 1 minute to register

### ISSUE THREAD

**Issue by hanzala-123** [jneilliii/OctoPrint-WemoSwitch#33]
The plugin is working but it takes over 1 minute to toggle the switch.

**Comment by jneilliii** [comment]
Can you please share screenshots of your settings?

**Comment by hanzala-123** [comment]
[image: image.png]

**Comment by jneilliii** [comment]
Sorry, but images don't come through on email replies. You'll have to open github and copy/paste a screenshot directly in your comment.

**Comment by dburr** [comment]
Seeing the exact same thing. Takes about a minute from hitting the lightning bolt icon to the Wemo actually responding (both turning on or off.)

Not sure if this is related or not, but the other day I launched the WeMo app on my phone and got a message something to the effect of "I found some unregistered WeMos on your network, would you like to register them to your account?" Not sure of the exact wording, because I quickly and instinctively tapped "yes" without thinking.

Screenshots of my Octoprint Wemo settings attached.
![wemo1](https://user-images.githubusercontent.com/1237762/89479990-113cc080-d749-11ea-8614-c5d246135601.png)
![wemo2](https://user-images.githubusercontent.com/1237762/89479991-11d55700-d749-11ea-9e3e-57f819ea7280.png)

**Comment by jneilliii** [comment]
Could I get you guys to enable debug logging restart OctoPrint and try it a couple of times? The go into OctoPrint's settings and grab the file plugin_wemoswitch_debug.log from the logging section and drag it here into a comment so I can evaluate a little more. Also if you don't mind please check in your developer console in your browser to see if there are any errors?

**Comment by dburr** [comment]
> Could I get you guys to enable debug logging restart OctoPrint and try it a couple of times? The go into OctoPrint's settings and grab the file plugin_wemoswitch_debug.log from the logging section and drag it here into a comment so I can evaluate a little more. Also if you don't mind please check in your developer console in your browser to see if there are any errors?

[console.log](https://github.com/jneilliii/OctoPrint-WemoSwitch/files/5032369/console.log)
[plugin_wemoswitch_debug.log](https://github.com/jneilliii/OctoPrint-WemoSwitch/files/5032370/plugin_wemoswitch_debug.log)

**Comment by jneilliii** [comment]
Curious @dburr if you have the same issue if you connect to OctoPrint via ip address instead of by name?
