### ISSUE TITLE
Cannot see the section to add a device

### ISSUE THREAD

**Issue by decofc** [jneilliii/OctoPrint-WemoSwitch#34]
Hello, I have been using this plugin for a while but I installed in a new Raspberry and once I installed this new version, I cannot see the devices section on top as before

![image](https://user-images.githubusercontent.com/67241751/88932920-bab51b00-d24c-11ea-8e15-a8606532e611.png)

**Comment by jneilliii** [comment]
Sorry about that @decofc I just released a new version that should fix this for you. Go into Software Update, click Advanced Options at the bottom and click the Force check for updates button. You should get the upgrade option, if you still have it installed. Otherwise, just install from the Plugin Manager again.
